vim.cmd 'packadd paq-nvim'
require'paq-nvim' {
  {'savq/paq-nvim', opt = true},
  'chaoren/vim-wordmotion',
  'dkarter/bullets.vim',
  'famiu/feline.nvim',
  'houtsnip/vim-emacscommandline',
  'kyazdani42/nvim-web-devicons',
  'lewis6991/gitsigns.nvim',
  'machakann/vim-sandwich',
  'neovim/nvim-lspconfig',
  'nvim-lua/plenary.nvim',
  'nvim-treesitter/nvim-treesitter',
  'rhysd/clever-f.vim',
  'srcery-colors/srcery-vim',
  'thinca/vim-visualstar',
  'tpope/vim-repeat',
  'tpope/vim-unimpaired',
  'tyru/caw.vim',
  'LnL7/vim-nix',
  'NovaDev94/vim-fish',
  'cespare/vim-toml',
  'aliou/bats.vim',
  'mnacamura/vim-fennel-syntax',
  'npxbr/glow.nvim',
}
