vim.cmd 'packadd paq-nvim'
local use = require'paq-nvim'.paq

use {'savq/paq-nvim', opt = true}
use 'chaoren/vim-wordmotion'
use 'dkarter/bullets.vim'
use 'famiu/feline.nvim'
use 'houtsnip/vim-emacscommandline'
use 'kyazdani42/nvim-web-devicons'
use 'lewis6991/gitsigns.nvim'
use 'machakann/vim-sandwich'
use 'neovim/nvim-lspconfig'
use 'nvim-lua/plenary.nvim'
use 'nvim-treesitter/nvim-treesitter'
use 'rhysd/clever-f.vim'
use 'srcery-colors/srcery-vim'
use 'thinca/vim-visualstar'
use 'tpope/vim-repeat'
use 'tpope/vim-unimpaired'
use 'tyru/caw.vim'
use 'LnL7/vim-nix'
use 'NovaDev94/vim-fish'
use 'cespare/vim-toml'
use 'aliou/bats.vim'
