require 'my.plugins.paq'

require 'my.plugins.null-ls'
require 'my.plugins.treesitter'
require 'my.plugins.sandwich'
require 'my.plugins.srcery'
require 'my.plugins.web-devicons'
require 'my.plugins.feline'
require 'my.plugins.gitsigns'
require 'my.plugins.lightspeed'
require 'my.plugins.bullets'
require 'my.plugins.glow'
require 'my.plugins.gfm-syntax'
require 'my.plugins.pandoc-syntax'
